name: Test8
on:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: [gen9randombattle, gen9ou]
    steps:
      - run: mkdir -p data && echo "model" > data/model.zip
      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: model-${{ matrix.format }}
          path: data/model.zip
